#!/bin/bash
set -ex
adb shell am force-stop com.qualcomm.ftcrobotcontroller
adb install  --fastdeploy ./TeamCode/build/outputs/apk/debug/TeamCode-debug.apk
#adb shell am start -n com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity
